// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/Jnmendza/uh/backend/internal/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type CreateMembershipInput struct {
	UserID         primitive.ObjectID      `json:"userId"`
	OrganizationID primitive.ObjectID      `json:"organizationId"`
	TierID         primitive.ObjectID      `json:"tierId"`
	Role           models.Role             `json:"role"`
	Status         models.MembershipStatus `json:"status"`
	PaymentStatus  models.PaymentStatus    `json:"paymentStatus"`
}

type CreateMembershipTierInput struct {
	OrganizationID primitive.ObjectID `json:"organizationId"`
	Name           string             `json:"name"`
	Price          float64            `json:"price"`
	Benefits       []string           `json:"benefits,omitempty"`
	IsActive       *bool              `json:"isActive,omitempty"`
}

type CreateOrganizationInput struct {
	Name             string                  `json:"name"`
	Type             models.OrganizationType `json:"type"`
	ParentID         *primitive.ObjectID     `json:"parentId,omitempty"`
	Subdomain        string                  `json:"subdomain"`
	LogoURL          *string                 `json:"logoUrl,omitempty"`
	PrimaryColor     *string                 `json:"primaryColor,omitempty"`
	SecondaryColor   *string                 `json:"secondaryColor,omitempty"`
	FollowedClubID   *string                 `json:"followedClubId,omitempty"`
	FollowedLeagueID *string                 `json:"followedLeagueId,omitempty"`
}

type CreateUserInput struct {
	Email        string              `json:"email"`
	FirstName    string              `json:"firstName"`
	LastName     string              `json:"lastName"`
	AuthProvider models.AuthProvider `json:"authProvider"`
	AvatarURL    *string             `json:"avatarUrl,omitempty"`
	GlobalRole   *models.GlobalRole  `json:"globalRole,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
