package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"time"

	"github.com/Jnmendza/uh/backend/graph/generated"
	"github.com/Jnmendza/uh/backend/graph/model"
	"github.com/Jnmendza/uh/backend/internal/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Date is the resolver for the date field.
func (r *eventResolver) Date(ctx context.Context, obj *models.Event) (string, error) {
	return obj.Date.Format(time.RFC3339), nil
}

// JoinedAt is the resolver for the joinedAt field.
func (r *membershipResolver) JoinedAt(ctx context.Context, obj *models.Membership) (string, error) {
	return obj.JoinedAt.Format(time.RFC3339), nil
}

// ExpiresAt is the resolver for the expiresAt field.
func (r *membershipResolver) ExpiresAt(ctx context.Context, obj *models.Membership) (*string, error) {
	if obj.ExpiresAt == nil {
		return nil, nil
	}
	t := obj.ExpiresAt.Format(time.RFC3339)
	return &t, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *messageResolver) CreatedAt(ctx context.Context, obj *models.Message) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrganizationInput) (*models.Organization, error) {
	org := &models.Organization{
		Name:      input.Name,
		Type:      models.OrganizationType(input.Type),
		Subdomain: input.Subdomain,
	}

	if input.LogoURL != nil {
		org.Branding.LogoURL = *input.LogoURL
	}
	if input.PrimaryColor != nil {
		org.Branding.PrimaryColor = *input.PrimaryColor
	}
	if input.SecondaryColor != nil {
		org.Branding.SecondaryColor = *input.SecondaryColor
	}
	if input.FollowedClubID != nil {
		org.Settings.FollowedClubID = *input.FollowedClubID
	}
	if input.FollowedLeagueID != nil {
		org.Settings.FollowedLeagueID = *input.FollowedLeagueID
	}

	if input.ParentID != nil {
		org.ParentID = input.ParentID
	}

	return r.OrgRepo.Create(ctx, org)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*models.User, error) {
	var globalRole models.GlobalRole = models.GlobalRoleUser
	if input.GlobalRole != nil {
		globalRole = *input.GlobalRole
	}
	
	avatarUrl := ""
	if input.AvatarURL != nil {
		avatarUrl = *input.AvatarURL
	}

	user := &models.User{
		Email:        input.Email,
		FirstName:    input.FirstName,
		LastName:     input.LastName,
		AuthProvider: input.AuthProvider,
		AvatarURL:    avatarUrl,
		GlobalRole:   globalRole,
	}

	return r.UserRepo.Create(ctx, user)
}

// CreateMembershipTier is the resolver for the createMembershipTier field.
func (r *mutationResolver) CreateMembershipTier(ctx context.Context, input model.CreateMembershipTierInput) (*models.MembershipTier, error) {
	isActive := true
	if input.IsActive != nil {
		isActive = *input.IsActive
	}

	benefits := []string{}
	if input.Benefits != nil {
		benefits = input.Benefits
	}

	tier := &models.MembershipTier{
		OrganizationID: input.OrganizationID,
		Name:           input.Name,
		Price:          input.Price,
		Benefits:       benefits,
		IsActive:       isActive,
	}

	return r.MembershipTierRepo.Create(ctx, tier)
}

// CreateMembership is the resolver for the createMembership field.
func (r *mutationResolver) CreateMembership(ctx context.Context, input model.CreateMembershipInput) (*models.Membership, error) {
	membership := &models.Membership{
		UserID:         input.UserID,
		OrganizationID: input.OrganizationID,
		TierID:         input.TierID,
		Role:           input.Role,
		Status:         input.Status,
		PaymentStatus:  input.PaymentStatus,
	}

	return r.MembershipRepo.Create(ctx, membership)
}

// CreatedAt is the resolver for the createdAt field.
func (r *organizationResolver) CreatedAt(ctx context.Context, obj *models.Organization) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *organizationResolver) UpdatedAt(ctx context.Context, obj *models.Organization) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id primitive.ObjectID) (*models.Organization, error) {
	return r.OrgRepo.GetByID(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	return r.UserRepo.GetAll(ctx)
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// Event returns generated.EventResolver implementation.
func (r *Resolver) Event() generated.EventResolver { return &eventResolver{r} }

// Membership returns generated.MembershipResolver implementation.
func (r *Resolver) Membership() generated.MembershipResolver { return &membershipResolver{r} }

// Message returns generated.MessageResolver implementation.
func (r *Resolver) Message() generated.MessageResolver { return &messageResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Organization returns generated.OrganizationResolver implementation.
func (r *Resolver) Organization() generated.OrganizationResolver { return &organizationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type eventResolver struct{ *Resolver }
type membershipResolver struct{ *Resolver }
type messageResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type organizationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
